### ISSUE TITLE
Unable to run visual regression tests on windows machine

### ISSUE THREAD

**Issue by amjadalibb** [julianburr/cypress-match-screenshot#15]
I am getting below error when I try to run my visual regression tests on windows machine, but it works fine on Mac. 

CypressError: cy.exec('mkdir -p cypress/match-screenshots/new') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
The syntax of the command is incorrect.
      at Object.cypressErr (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:68154:11)
      at Object.throwErr (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:68119:18)
      at Object.throwErrByPath (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:68146:17)
      at https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:57819:23
      at tryCatcher (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:7091:23)
      at Promise._settlePromiseFromHandler (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:5113:31)
      at Promise._settlePromise (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:5170:18)
      at Promise._settlePromise0 (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:5215:10)
      at Promise._settlePromises (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:5294:18)
      at Async._drainQueue (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:2023:16)
      at Async._drainQueues (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:2033:10)
      at Async.drainQueues (https://www-06.sit.qantasbusinessrewards.com/__cypress/runner/cypress_runner.js:1907:14)
      at <anonymous>

**Comment by amjadalibb** [comment]
This is a duplicate of issue 
https://github.com/julianburr/cypress-match-screenshot/issues/11
